Repository deegree/deegree-ogcapi, pull requests merged in 2022-04, with the labels that each got.

#16 Fixes #15 sets same jersey for all jersey modules
  pom.xml
Labels: bug, dependencies

#21 Added README with sponsors
  README.md
  deegree-ogcapi-documentation/src/main/asciidoc/images/Logo_deegree.png
  sponsor_lgb.jpg
  sponsor_lgv.png
Labels: documentation

#22 Enhanced log messages
  deegree-ogcapi-config-htmlview/src/main/java/org/deegree/services/oaf/config/htmlview/HtmlViewConfigResource.java
  deegree-ogcapi-config-htmlview/src/main/java/org/deegree/services/oaf/config/htmlview/HtmlViewConfiguration.java
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OafResource.java
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OgcApiFeatures.java
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/domain/html/HtmlPageConfiguration.java
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/DatasetMetadata.java
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/OafDatasetConfiguration.java
Labels: enhancement

#23 Upgrade to log4j2
  deegree-ogcapi-features/pom.xml
  deegree-ogcapi-features/src/main/resources/log4j.properties
  deegree-ogcapi-features/src/test/resources/log4j.properties
  deegree-ogcapi-features/src/test/resources/log4j2.properties
  deegree-ogcapi-webapp/deegree-ogcapi-webapp-oracle/src/main/resources/log4j.properties
  deegree-ogcapi-webapp/deegree-ogcapi-webapp-oracle/src/main/resources/log4j2.properties
  deegree-ogcapi-webapp/deegree-ogcapi-webapp-postgres/src/main/resources/log4j.properties
  deegree-ogcapi-webapp/deegree-ogcapi-webapp-postgres/src/main/resources/log4j2.properties
  deegree-ogcapi-webapp/pom.xml
  pom.xml
Labels: enhancement, dependencies

#27 Fix registration of CRS in HTML view
  deegree-ogcapi-features/src/main/resources/collection.html
Labels: bug
