Repository deegree/deegree-ogcapi, pull requests merged in 2023-05, with the labels that each got.

#80 Add "openapi" alias for api endpoint
  deegree-ogcapi-documentation/src/main/asciidoc/usage.adoc
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/filter/OpenApiAliasFilter.java
  deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/resource/OpenApiTest.java
Labels: enhancement

#94 Dockerfile health check fix and small improvements
  Dockerfile
  README.md
  docker/liveness-check.sh
Labels: build

#95 Fix link relation type to OpenAPI specification
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/link/LinkBuilder.java
  deegree-ogcapi-features/src/main/resources/landingpage.html
  deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/resource/LandingPageTest.java
Labels: bug

#96 Add itemType in collection HTML
  deegree-ogcapi-features/src/main/resources/collection.html
Labels: enhancement

#82 Add OpenAPI description also in YAML format
  deegree-ogcapi-documentation/src/main/asciidoc/configuration.adoc
  deegree-ogcapi-documentation/src/main/asciidoc/usage.adoc
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OgcApiFeaturesMediaType.java
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/resource/OpenApi.java
  deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/resource/OpenApiCorsTest.java
  deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/resource/OpenApiTest.java
Labels: enhancement

#79 fix: test should be independent of system time zone
  deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/TestData.java
  deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/domain/collections/CollectionsIT.java
  deegree-ogcapi-features/src/test/resources/org/deegree/services/oaf/domain/collections/expectedCollection.json
  deegree-ogcapi-features/src/test/resources/org/deegree/services/oaf/domain/collections/expectedCollections.json
Labels: enhancement

#78 Exclude dependencies that are included in Java 11+
  deegree-ogcapi-config/pom.xml
  deegree-ogcapi-features/pom.xml
  pom.xml
Labels: enhancement, dependencies, build
