Repository deegree/deegree-ogcapi, pull requests merged in 2023-12, with the labels that each got.

#107 Upgrade maven plugins to latest bugfix version
  deegree-ogcapi-webapp/pom.xml
  pom.xml
Labels: dependencies, build

#108 Upgrade deegree and jaxb to latest bugfix version
  pom.xml
Labels: dependencies

#98 Relocate schema files for deegree OGCAPI to schemas/ogcapi
  deegree-ogcapi-config-htmlview/src/main/java/org/deegree/services/oaf/config/htmlview/HtmlViewConfigProvider.java
  deegree-ogcapi-config-htmlview/src/main/resources/META-INF/schemas/ogcapi/example_htmlview.xml
  deegree-ogcapi-config-htmlview/src/main/resources/META-INF/schemas/ogcapi/htmlview.xsd
  deegree-ogcapi-datasets/src/main/java/org/deegree/services/oaf/config/datasets/DatasetsConfigProvider.java
  deegree-ogcapi-datasets/src/main/resources/META-INF/schemas/ogcapi/datasets.xsd
  deegree-ogcapi-datasets/src/main/resources/META-INF/schemas/ogcapi/datasets/3.4.0/example.xml
  deegree-ogcapi-datasets/src/main/resources/META-INF/schemas/ogcapi/example_datasets.xml
  deegree-ogcapi-documentation/src/main/asciidoc/configuration.adoc
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OafProvider.java
  deegree-ogcapi-features/src/main/resources/META-INF/schemas/ogcapi/example_features.xml
  deegree-ogcapi-features/src/main/resources/META-INF/schemas/ogcapi/features.xsd
Labels: enhancement

#97 Added deegree-ogcapi-schema, Deploy deegree-ogcapi-schema and deegree-ogcapi-documentation
  deegree-ogcapi-schema/.gitignore
  deegree-ogcapi-schema/pom.xml
  deegree-ogcapi-schema/src/main/assembly/schemas.xml
  jenkinsfiles/build/Jenkinsfile
  pom.xml
Labels: enhancement

#111 Removed deploy step from pipeline
  jenkinsfiles/build/Jenkinsfile
  pom.xml
Labels: build
