Repository deegree/deegree-ogcapi, pull requests merged in 2025-04, with the labels that each got.

#148 Minor improvements to the documentation
  deegree-ogcapi-documentation/src/main/asciidoc/configuration.adoc
  deegree-ogcapi-documentation/src/main/asciidoc/index.adoc
  deegree-ogcapi-documentation/src/main/asciidoc/installation.adoc
  deegree-ogcapi-documentation/src/main/asciidoc/intro.adoc
Labels: documentation

#151 Upgraded dependencies deegree to 3.5.12, swagger to 2.2.30 and maven plugins
  deegree-ogcapi-documentation/pom.xml
  deegree-ogcapi-webapp/pom.xml
  pom.xml
Labels: dependencies

#150 Support of FILTER parameters with T_AFTER
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/cql2/Cql2FilterVisitor.java
  deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/DeegreeQueryBuilder.java
  deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/cql2/Cql2ParserTest.java
Labels: enhancement

#153 Changed deployment format to exploded of deegree-ogcapi.war file in container image
  docker/1.3/Dockerfile
Labels: enhancement
